#!/bin/bash

USAGE='Usage: vim-dev program-name'

## ARGUMENTS
##############################

while getopts ":e:" opt; do
  case $opt in
    h)
      echo $USAGE
      exit 0
      ;;
    e)
      VENV=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
shift $((OPTIND-1))

PROG=$1

## ASSERTIONS
##############################

if [ -z $1 ] ; then
  echo $USAGE
  exit 1
fi


## MAIN
##############################

if [ -n "$VENV" ] ; then
  if [ -d $(pwd)/$VENV ] ; then
    ENV="source $(pwd)/$VENV/bin/activate"
  else
    echo "Python virtual environment doesn't exist. Ignoring..."
  fi
fi
    
tmux new-session -d 'vim'

if [ -n "$ENV" ] ; then
  tmux split-window -v "$ENV && $PROG"
else
  tmux split-window -v $PROG
fi

tmux -2 attach-session -d

